# Generated by Django 2.1.7 on 2019-02-21 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycle', '0002_auto_20190221_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='image',
            field=models.CharField(max_length=190),
        ),
    ]
